print("what is your name human?")
name = str(input())
print("How old are you?")
age = int(input())
print("How tall are you?")
height = float(input())
print("How much do you weigh?")
weight = int(input())
bmi = weight / (height * height)
print(name + "," + "you are " + str(age) + " and your bmi is " + str(bmi))